{% set name = "titlecase" %}
{% set version = "0.13.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/titlecase-{{ version }}.tar.gz
  sha256: 9b1d43db4c3499e47a45d4bd202068261fd585de6bd8e6313a8868533cfa4690

build:
  number: 0
  noarch: python
  entry_points:
    - titlecase = titlecase.__init__:cmd
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - nose >=1.0
    - pip
    - python >=3.4
    - regex >=2020.4.4
  run:
    - python >=3.4

test:
  imports:
    - titlecase
  commands:
    - pip check
    - titlecase --help
  requires:
    - pip

about:
  home: https://github.com/ppannuto/python-titlecase
  summary: Python Port of John Gruber's titlecase.pl
  license: Apache-2.0
  # License file manually packaged. See: https://github.com/ppannuto/python-titlecase/pull/71
  license_file: .eggs/regex-2020.11.13-py3.7-linux-x86_64.egg/EGG-INFO/LICENSE.txt

extra:
  recipe-maintainers:
    - brocksam
    - thewchan
